In [1]:
from keras.datasets import boston_housing
import numpy as np

Using TensorFlow backend.


In [2]:
(training_x, training_y), (test_x, test_y) = boston_housing.load_data()

In [3]:
training_x[:5]

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        6.14200e+00, 9.17000e+01, 3.97690e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, 0.00000e+00, 4.15000e-01,
        7.61000e+00, 1.57000e+01, 6.27000e+00, 2.00000e+00, 3.48000e+02,
        1.47000e+01, 3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.31000e-01,
        4.97000e+00, 1.00000e+02, 1.33250e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.75520e+02, 3.26000e+00],
       [3.96100e-02, 0.00000e+00, 5.19000e+00, 0.00000e+00, 5.15000e-01,
        6.03700e+00, 3.45000e+01, 5.98530e+00, 5.00000e+00, 2.24000e+02,
        2.02000e+01, 3.96900e+02, 8.01000e+00],
       [3.69311e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.13000e-01,
        6.37600e+00, 8.84000e+01, 2.56710e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.91430e+02, 1.46500e+01]])

In [4]:
training_x.shape

(404, 13)

In [5]:
training_x.mean(axis=0)

array([3.74511057e+00, 1.14801980e+01, 1.11044307e+01, 6.18811881e-02,
       5.57355941e-01, 6.26708168e+00, 6.90106436e+01, 3.74027079e+00,
       9.44059406e+00, 4.05898515e+02, 1.84759901e+01, 3.54783168e+02,
       1.27408168e+01])

In [6]:
training_x.var(axis=0)

array([8.51798073e+01, 5.63505796e+02, 4.62790747e+01, 5.80519067e-02,
       1.37236180e-02, 5.02551441e-01, 7.78748377e+02, 4.11156931e+00,
       7.54741937e+01, 2.76119724e+04, 4.82969580e+00, 8.83498510e+03,
       5.24981521e+01])

In [7]:
def normalize(data):
    return (data - data.mean(axis=0)) / (data.std(axis=0))

In [8]:
training_x = normalize(training_x)

In [86]:
first_layer_size = 128
(num_samples, num_features) = training_x.shape
lr = 0.01
np.random.seed(100)
W1 = np.random.randn(num_features, first_layer_size)
B1 = np.random.randn(1, first_layer_size)
W2 = np.random.randn(first_layer_size, 1)
B2 = np.random.random()
a1 = np.zeros((num_samples, first_layer_size))
z1 = np.zeros((num_samples, first_layer_size))
a2 = np.zeros((num_samples, 1))
def forward():
    global W2, W1, B1, B2, a1, z1, a2
    a1 = np.dot(training_x, W1) + B1
    z1 = np.tanh(a1)
    a2 = np.dot(z1, W2) + B2
    loss = 1/num_samples * np.sum((a2 - training_y.reshape(len(training_y), 1))**2, axis=0)[0]
    return loss

In [87]:
def backward():
    global W2, W1, B1, B2, a1, z1, a2
    dla2 =  2/num_samples * np.sum(a2 - training_y.reshape(len(training_y), 1), axis=1)
    dla2 = dla2.reshape(dla2.shape[0], 1)
    dw2 = z1.T.dot(dla2)
    db2 = dla2
    dw1 = training_x.T.dot((dla2.dot(W2.T) * (1 - np.tanh(a1) ** 2)))
    db1 = np.sum(dla2.dot(W2.T) * (1 - np.tanh(a1) ** 2), axis=0, keepdims=True)
    
    W1 -= lr * dw1
    B1 -= lr * db1
    W2 -= lr * dw2
    B2 -= lr * db2

In [88]:
for i in range(1000):
    loss = forward()
    backward()
    print(f"{i}: {loss}")

0: 508.9916456301904
1: 203.74776940720565
2: 117.85464881558121
3: 87.5350259281321
4: 73.09741654570394
5: 64.2573863410253
6: 57.95815589532467
7: 53.1109761105577
8: 49.21343655769699
9: 45.97780042470959
10: 43.219832303601095
11: 40.81760355307812
12: 38.68967977439099
13: 36.78074371333833
14: 35.05208775697126
15: 33.475778182105785
16: 32.03136409010371
17: 30.704004648762062
18: 29.48294091018192
19: 28.35966205251903
20: 27.32607992239766
21: 26.373612881609002
22: 25.49340190809055
23: 24.67698682736572
24: 23.916802975075793
25: 23.206345685815123
26: 22.540118218528868
27: 21.913495657701926
28: 21.322578635419717
29: 20.76406433399126
30: 20.235139735645856
31: 19.733394145619464
32: 19.256746505820068
33: 18.80338386075544
34: 18.371708831831228
35: 17.960295338454387
36: 17.567852640857833
37: 17.19319787237711
38: 16.835236683434708
39: 16.49295080779402
40: 16.165390721613964
41: 15.851671371243054
42: 15.550969210828166
43: 15.26251934056171
44: 14.985612146136358
4

399: 2.674417057856087
400: 2.669438110926244
401: 2.6644799091834
402: 2.6595422867989407
403: 2.6546250797438344
404: 2.6497281257658494
405: 2.644851264367095
406: 2.639994336781935
407: 2.635157185955218
408: 2.6303396565208694
409: 2.6255415947807763
410: 2.6207628486840315
411: 2.616003267806463
412: 2.6112627033304863
413: 2.6065410080252733
414: 2.6018380362271882
415: 2.597153643820548
416: 2.5924876882186583
417: 2.5878400283451164
418: 2.5832105246154256
419: 2.5785990389188456
420: 2.5740054346005294
421: 2.569429576443922
422: 2.564871330653404
423: 2.5603305648371917
424: 2.5558071479904974
425: 2.551300950478917
426: 2.5468118440220477
427: 2.542339701677371
428: 2.537884397824331
429: 2.5334458081486537
430: 2.529023809626893
431: 2.5246182805111737
432: 2.5202291003141704
433: 2.515856149794278
434: 2.5114993109409878
435: 2.507158466960481
436: 2.5028335022613994
437: 2.4985243024408255
438: 2.4942307542704443
439: 2.4899527456828916
440: 2.485690165758296
441: 2.4814

750: 1.6059551933752159
751: 1.6040134871917906
752: 1.6020756273145373
753: 1.6001416023023474
754: 1.5982114007578707
755: 1.596285011327234
756: 1.5943624226997526
757: 1.5924436236076505
758: 1.5905286028257897
759: 1.588617349171388
760: 1.5867098515037634
761: 1.5848060987240584
762: 1.582906079774989
763: 1.5810097836405776
764: 1.5791171993459172
765: 1.5772283159568985
766: 1.575343122579987
767: 1.5734616083619664
768: 1.5715837624897078
769: 1.56970957418993
770: 1.5678390327289644
771: 1.5659721274125378
772: 1.5641088475855378
773: 1.562249182631794
774: 1.560393121973854
775: 1.5585406550727778
776: 1.556691771427918
777: 1.5548464605767065
778: 1.5530047120944566
779: 1.5511665155941574
780: 1.5493318607262634
781: 1.547500737178509
782: 1.5456731346757016
783: 1.5438490429795393
784: 1.5420284518884144
785: 1.5402113512372262
786: 1.5383977308971966
787: 1.5365875807756908
788: 1.5347808908160336
789: 1.532977650997333
790: 1.5311778513343068
791: 1.5293814818771057
792

http://mccormickml.com/2014/03/04/gradient-descent-derivation/

https://towardsdatascience.com/coding-neural-network-forward-propagation-and-backpropagtion-ccf8cf369f76

https://machinelearningmastery.com/implement-backpropagation-algorithm-scratch-python/