In [2]:
from keras.datasets import boston_housing
import numpy as np

In [20]:
(training_x, training_y), (test_x, test_y) = boston_housing.load_data()

In [21]:
training_x[:5]

array([[1.23247e+00, 0.00000e+00, 8.14000e+00, 0.00000e+00, 5.38000e-01,
        6.14200e+00, 9.17000e+01, 3.97690e+00, 4.00000e+00, 3.07000e+02,
        2.10000e+01, 3.96900e+02, 1.87200e+01],
       [2.17700e-02, 8.25000e+01, 2.03000e+00, 0.00000e+00, 4.15000e-01,
        7.61000e+00, 1.57000e+01, 6.27000e+00, 2.00000e+00, 3.48000e+02,
        1.47000e+01, 3.95380e+02, 3.11000e+00],
       [4.89822e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 6.31000e-01,
        4.97000e+00, 1.00000e+02, 1.33250e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.75520e+02, 3.26000e+00],
       [3.96100e-02, 0.00000e+00, 5.19000e+00, 0.00000e+00, 5.15000e-01,
        6.03700e+00, 3.45000e+01, 5.98530e+00, 5.00000e+00, 2.24000e+02,
        2.02000e+01, 3.96900e+02, 8.01000e+00],
       [3.69311e+00, 0.00000e+00, 1.81000e+01, 0.00000e+00, 7.13000e-01,
        6.37600e+00, 8.84000e+01, 2.56710e+00, 2.40000e+01, 6.66000e+02,
        2.02000e+01, 3.91430e+02, 1.46500e+01]])

In [22]:
training_x.shape

(404, 13)

In [23]:
training_x.mean(axis=0)

array([3.74511057e+00, 1.14801980e+01, 1.11044307e+01, 6.18811881e-02,
       5.57355941e-01, 6.26708168e+00, 6.90106436e+01, 3.74027079e+00,
       9.44059406e+00, 4.05898515e+02, 1.84759901e+01, 3.54783168e+02,
       1.27408168e+01])

In [24]:
training_x.var(axis=0)

array([8.51798073e+01, 5.63505796e+02, 4.62790747e+01, 5.80519067e-02,
       1.37236180e-02, 5.02551441e-01, 7.78748377e+02, 4.11156931e+00,
       7.54741937e+01, 2.76119724e+04, 4.82969580e+00, 8.83498510e+03,
       5.24981521e+01])

In [25]:
def normalize(data):
    return (data - data.mean(axis=0)) / (data.std(axis=0))

In [26]:
training_x = normalize(training_x)

In [48]:
first_layer_size = 128
(num_samples, num_features) = training_x.shape

W1 = np.random.randn(num_features, first_layer_size)
B1 = np.random.randn(1, first_layer_size)
W2 = np.random.randn(first_layer_size, 1)
B2 = np.random.random()

a1 = np.dot(training_x, W1) + B1
z1 = np.tanh(a1)
a2 = np.dot(z1, W2) + B2
loss = 1/num_samples * np.sum((a2 - training_y.reshape(len(training_y), 1))**2, axis=0)[0]

778.523980092233


In [75]:
dla2 = (2/num_samples * np.sum(a2 - training_y.reshape(len(training_y), 1), axis=1))
dla2 = dla2.reshape(dla2.shape[0], 1)
dw2 = z1.T.dot(dla2)
db2 = dla2
dz1 = dla2.dot(W2.T)

dw1 = (dz1 * (1 - np.tanh(a1)**2))
dw1 = training_x.T.dot(dw1)


(404, 128)


http://mccormickml.com/2014/03/04/gradient-descent-derivation/

https://towardsdatascience.com/coding-neural-network-forward-propagation-and-backpropagtion-ccf8cf369f76

https://machinelearningmastery.com/implement-backpropagation-algorithm-scratch-python/